version: '3.8'

services:
  pong:
    build: .
    command: ["python3", "cli.py"]
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - display

  display:
    image: jess/firefox
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5900:5900"
